/* Generated by YAKINDU Statechart Tools for Arduino v0.5.0 */

#ifndef ZOWI_DEMOCONNECTOR_H
#define ZOWI_DEMOCONNECTOR_H

#include <Arduino.h>
#include "../src-gen/HardwareConnector.h"
#include "../src-gen/Zowi_Demo.h"
#include <BitbloqZowi.h>

//---------------------------------------------------------
//-- Configuration of pins where the servos are attached
/*
         ---------------
        |               |
        |     O   O     |
        |               |
 YR ==> |               | <== YL
         ---------------
            ||     ||
            ||     ||
            ||     ||
 RR ==>   -----   ------  <== RL
          -----   ------
*/

 #define PIN_YL 2 //servo[0]
 #define PIN_YR 3 //servo[1]
 #define PIN_RL 4 //servo[2]
 #define PIN_RR 5 //servo[3]
//---------------------------------------------------------


class Zowi_DemoConnector: public HardwareConnector {
public:
	Zowi_DemoConnector(Zowi_Demo* statemachine);

	inline ~Zowi_DemoConnector();

	/*
	 * Initialize the hardware.
	 */
	void init();

	/*
	 * Raise state machine events before processing them in the state machine's runCycle().
	 */
	void raiseEvents();

	/*
	 * Update the hardware depending on the state machine's state.
	 */
	void syncState();

	/*
	 * Optimize power consumption by turning off modules that are not needed.
	 * Return one of the following sleep states:
	 * SLEEP_MODE_IDLE, SLEEP_MODE_ADC, SLEEP_MODE_PWR_DOWN, SLEEP_MODE_PWR_SAVE,
	 * SLEEP_MODE_STANDBY, SLEEP_MODE_EXT_STANDBY
	 * The returned sleep mode is just a recommendation, the actual timer implementation
	 * may not support the given sleep mode.
	 */
	uint8_t prepareSleepMode();
	
private:
	Zowi* zowi;

	Zowi_Demo* statemachine;

	boolean obstacleDetected();

	boolean noiseDetected();
};
	
Zowi_DemoConnector::~Zowi_DemoConnector() {
}

#endif /* ZOWI_DEMOCONNECTOR_H */
